package com.grash.model.enums.webhook;

public enum WebhookEvent {

    ASSET_STATUS_CHANGE,
    METER_TRIGGER_STATUS_CHANGE,
    NEW_ASSET,
    NEW_CATEGORY_ON_WORK_ORDER,
    NEW_COMMENT_ON_WORK_ORDER,//TODO
    NEW_LOCATION,
    NEW_PART,
    NEW_PURCHASE_ORDER,//TODO
    NEW_VENDOR,
    NEW_WORK_ORDER,
    NEW_REQUEST,
    PART_CHANGE,
    PART_DELETE,
    PART_QUANTITY_CHANGED,
    PURCHASE_ORDER_CHANGE,//TODO
    PURCHASE_ORDER_STATUS_CHANGE,//TODO
    WORK_ORDER_CHANGE,
    WORK_ORDER_DELETE,
    WORK_ORDER_OVERDUE,//TODO
    WORK_ORDER_STATUS_CHANGE,
    WORK_REQUEST_STATUS_CHANGE
}